[tool.black]
line-length = 120

[tool.isort]
profile = "black"
line_length = 120

[tool.pylint.messages_control]
max-line-length = 120
disable = [
    "missing-module-docstring",
    "no-value-for-parameter",  # pylint issue with function wrapper
]


[tool.coverage.run]
branch = true

[tool.coverage.report]
fail_under = 90
