on: [push]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.8, 3.9]
    env:
      AWS_DEFAULT_REGION: us-east-1
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install requirements
      run: make dependencies
    - name: Format and Lint
      run: make lint
    - name: Run unit tests with coverage
      run: make unit-test
    - name: Set up Terraform
      uses: hashicorp/setup-terraform@v2
    - name: Run integration tests
      run: make integration-test
    - name: Clean up local infra
      run: make clean
